AmmarFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('MyUnifoorm/', include('MyUnifoorm.urls')),  # Include your app's URLs
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyUnifoorm/urls.py
from django.urls import path
from. import views

urlpatterns = [
    path('', views.main, name='main'),

    #login
    path('login/', views.login_view, name='login'),
    path('login/signup', views.signup, name='signup'),

    #profile
    path('profile/<str:email>/', views.profile, name='profile'),
    path('logout/', views.logout_view, name='logout'),
    

    #product
    path('product/', views.product_view, name='product'),

    #Order
    path('product/order/<str:product_id>/', views.order, name='order'),
    path('product/order/<int:order_id>/review/', views.add_review, name='add_review'),
    path('product/orderhistory/', views.my_orders, name='my_orders'),
    path('product/delete_order/<int:order_id>/', views.delete_order, name='delete_order'),
            path('product/update_order/<int:order_id>/', views.update_order, name='update_order'),

    #Review
    path('product/review/<str:product_id>/', views.review, name='review'),

    
]

MyUnifoorm/models.py
from django.db import models

class User(models.Model):
    Email = models.CharField(max_length=25 ,primary_key= True)
    Password  = models.CharField(max_length=12)
    Name = models.TextField()
    PhoneNumber = models.CharField(max_length=13)
    Address = models.TextField()
    
class Product(models.Model):
    ProductID = models.CharField(max_length=5,primary_key=True)
    ProductName = models.TextField()
    ProdImg = models.ImageField(upload_to="productpic" ,default="null")
    Description = models.TextField()
    Price = models.FloatField()
    Brand = models.CharField(max_length=20)
    Size = models.CharField(max_length=4)
    Color = models.CharField(max_length=10)
    Quantity = models.IntegerField()
    Material = models.CharField(max_length=20)


class Order(models.Model):
        
    OrderID  = models.AutoField( primary_key= True)
    Email = models.ForeignKey(User,on_delete=models.CASCADE)
    ProductID = models.ForeignKey(Product,on_delete=models.CASCADE)
    Qty = models.IntegerField(default=0)
    OrderDate = models.DateField()
    OrderStatus = models.CharField(max_length=20)
    TotalAmount = models.FloatField()



class Review(models.Model):
    ReviewID = models.AutoField(primary_key=True)
    OrderID = models.ForeignKey(Order , on_delete=models.CASCADE)
    Email = models.ForeignKey(User, on_delete=models.CASCADE)
    Comment = models.TextField()
    ReviewDate = models.DateField()
    

MyUnifoorm/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import User,Product,Order,Review
import datetime
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
# Create your views here.

def main(request):
    email = request.session.get('user_email')
    if request.user.is_authenticated:
        user = request.user
        print("User is authenticated:", user)  # Debug statement
    else:
        user = None
    return render(request, 'main.html', {'user': user})




def signup(request):
    user=User.objects.all().values()
    if request.method == 'POST':
        email = request.POST.get('Email')
        password = request.POST.get('Password')
        name = request.POST.get('Name')
        phoneNumber = request.POST.get('PhoneNumber')
        address = request.POST.get('Address')

        user = User(Email=email, Password=password, Name=name, PhoneNumber=phoneNumber , Address = address)
        user.save()
        return redirect('login')  
    return render(request,'signup.html')



def login_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = User.objects.filter(Email=email, Password=password).first()
        if user:
            request.session['user_email'] = user.Email
            request.user = user  # Set the request.user object
            return redirect('main')
        else:
            return render(request, 'login.html', {'error': 'Invalid email or password'})
    return render(request, 'login.html')


    

def profile(request, email):
    email = request.session.get('user_email')
    if email:
        try:
            user = User.objects.get(Email=email)

            if request.method == 'POST':
                password = request.POST.get('Password')
                name = request.POST.get('Name')
                phone_number = request.POST.get('PhoneNumber')
                address = request.POST.get('Address')

                if password and len(password) <= 12:
                    user.Password = password
                if name:
                    user.Name = name
                if phone_number and len(phone_number) <= 13:
                    user.PhoneNumber = phone_number
                if address:
                    user.Address = address

                user.save()
                messages.success(request, 'Profile updated successfully!')
                return redirect('profile', email=email)
            return render(request, 'profile.html', {'user': user})
        except User.DoesNotExist:
            return redirect('login')  # Redirect to login if user does not exist
    else:
        return redirect('login')

def logout_view(request):
    request.session.flush()  # Clear all session data
    return redirect('main')

def product_view(request):
    products = Product.objects.all()
    return render(request, 'product.html', {'products': products})


def order(request, product_id):
    email = request.session.get('user_email')
    if not email:
        return redirect('login')  # Redirect to login if no email is found in session
    
    user = User.objects.get(Email=email)
    product = Product.objects.get(ProductID=product_id)

    if request.method == 'POST':
        quantity = int(request.POST.get('quantity'))
        
        if quantity > product.Quantity:
            return HttpResponse("Not enough stock available.")
        
        total_amount = quantity * product.Price
        order = Order(
            Email=user,
            ProductID=product,
            Qty=quantity,  # added this field
            OrderDate=datetime.date.today(),
            OrderStatus='Successful',
            TotalAmount=total_amount
        )
        order.save()
        
        # Reduce the product quantity
        product.Quantity -= quantity
        product.save()  # Save the updated product object
        

        return render(request, 'receipt.html', {'order': order, 'user': user, 'product': product})

    else:

        return render(request, 'order.html', {'user': user, 'product': product, })

def my_orders(request):
    orders = Order.objects.filter(Email=request.session.get('user_email'))
    return render(request, 'orderhistory.html', {'orders': orders})
def update_order(request, order_id):
    order = Order.objects.get(pk=order_id)
    user = order.Email
    old_qty = order.Qty  # Store the old quantity to adjust stock later

    if request.method == 'POST':
        new_qty = int(request.POST.get('qty'))
        new_address = request.POST.get('address')

        # Update order quantity and total amount
        order.Qty = new_qty
        order.TotalAmount = order.ProductID.Price * new_qty
        
        # Update user's shipping address
        user.Address = new_address
        user.save()

        # Adjust stock
        product = order.ProductID
        product.Quantity += (old_qty - new_qty)  # Increase or decrease stock based on the new quantity
        product.save()

        # Save order changes
        order.save()

        messages.success(request, 'Order updated successfully')
        return redirect('my_orders')
    
    return render(request, 'update_order.html', {'order': order})

def delete_order(request, order_id):
    order = Order.objects.get(pk=order_id)
    product = order.ProductID

    # Adjust stock
    product.Quantity += order.Qty
    product.save()

    # Delete the order
    order.delete()

    messages.success(request, 'Order canceled successfully')
    return redirect('my_orders')
# views.py

def add_review(request, order_id):
    order = Order.objects.get(OrderID=order_id)
    user = User.objects.get(Email=request.session.get('user_email'))
    if request.method == 'POST':
        comment = request.POST.get('comment')
        review = Review(
            OrderID=order,
            Email=user,
            Comment=comment,
            ReviewDate=datetime.date.today()
        )
        review.save()
        # Redirect to the review page for this product
        return redirect('review', product_id=order.ProductID.ProductID)
    return render(request, 'review.html', {'order': order}) #add_review.html


def review(request, product_id):

    product = Product.objects.get(ProductID=product_id)
    reviews = Review.objects.filter(OrderID__ProductID=product)
    return render(request, 'review.html', {'reviews': reviews, 'product': product})

MyUnifoorm/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login & Create Account</title>
    <link rel="stylesheet" href="\static\signup.css">
    
</head>
<style>
                body {
                margin: 0;
                padding: 0;

            }
            header {
            background-color: #6d0505;
            color: #fff;
            padding: 2px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Added shadow for depth */
            position: sticky; /* Make header sticky */
            top: 0; /* Stick to the top */
            z-index: 1000; /* Ensure it stays on top */
        }

        .logo {
            font-size: 30px;
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
            font-weight: 600;
            margin-left: 2%;
        }

        nav {
            margin-left: auto;
        }

        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            display: flex;
        }

        nav li {
            margin-right: 20px;
        }

        nav a {
            color: #fff;
            text-decoration: none;
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
            font-weight: 600;
            position: relative;
            padding: 5px 0; /* Added padding for better click area */
        }

        nav a::after {
            content: '';
            display: block;
            width: 0;
            height: 2px;
            background: #ccc;
            transition: width .3s;
            position: absolute;
            bottom: 0;
            left: 0;
        }

        nav a:hover::after {
            width: 100%; /* Animate underline on hover */
            background-color: #ccc;
        }
        /* Login and Create Account Styles */

.container {
  max-width: 600px;
  margin: 40px auto;
  padding: 70px;
  background-color: #f9f9f9;
  border: 1px solid #ddd;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  border-radius: 1%;
}

h1 {
  font-size: 24px;
  margin-bottom: 10px;
}

label {
  display: block;
  margin-bottom: 10px;
}

input[type="text"], input[type="password"] {
  width: 100%;
  height: 40px;
  margin-bottom: 20px;
  padding: 10px;
  border: 1px solid #ccc;
}

input[type="checkbox"] {
  margin-right: 10px;

}

button[type="submit"] {
  background-color: #4CAF50;
  color: #fff;
  padding: 10px 20px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

button[type="submit"]:hover {
  background-color: #3e8e41;
}

.info {
  font-size: 14px;
  color: #666;
  margin-bottom: 20px;
}

.terms {
  font-size: 14px;
  color: #666;
  margin-top: 20px;
}

.terms a {
  text-decoration: none;
  color: #666;
}

.terms a:hover {
  text-decoration: underline;
}

.create-account {
  margin-top: 40px;
}

.create-account button[type="button"] {
  background-color: #4CAF50;
  color: #fff;
  padding: 10px 20px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

.create-account button[type="button"]:hover {
  background-color: #3e8e41;
}

</style>
<body>
    <header>
        <div class="logo">
            <p>MyUniform.com</p>
        </div>
        <nav>
            <ul>
                <li><a href="/MyUnifoorm/">BACK TO HOME</a></li>
                
            </ul>
        </nav>
    </header>   
    <div class="container">
        <h1>LOGIN to MyUniform</h1>
        <p>Log in with your email address and password.</p>

            <form method="post">
                {% csrf_token %}
                <label for="email">Email Address <span class="required">*</span></label>
                <input type="text" id="email" name="email" placeholder="Enter a valid email">
                <label for="password">Password <span class="required">*</span></label>
                <input type="password" id="password" name="password" placeholder="Enter password">
                <label><input type="checkbox" id="showPassword"> Show my password</label>

                <p class="info">Password must be at least 8 characters, and contain both letters and numbers. Only these symbols can be used -_.@</p>
                {% if error %}
                    <p style="color: red;">{{ error }}</p>
                {% endif %}
                <center><button type="submit" style="width: 200px;">LOG IN</button></center>
                <br>
                <br>
                <center><a href="#" style="color: #555252;">Forget your password?</a><br></center>
                <center><a href="signup" style="color: #555252; ">Don't have an account?</a></center>
                
            </form>
        <div class="terms">
            <a href="#">TERMS OF USE</a> | <a href="#">PRIVACY POLICY</a>
        </div>
    </div>
    <script>
        const passwordInput = document.getElementById('password');
        const showPasswordCheckbox = document.getElementById('showPassword');

        showPasswordCheckbox.addEventListener('change', handleCheckboxClick, false);

        function handleCheckboxClick() {
        if (this.checked) {
            passwordInput.type = 'text';
        } else {
            passwordInput.type = 'password';
        }
        }
    </script>
</body>
</html>

MyUnifoorm/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Page</title>
    <style>
        body {
            margin: 0;
            padding: 0;

        }
        header {
            background-color: #6d0505;
            color: #fff;
            padding: 2px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Added shadow for depth */
            position: sticky; /* Make header sticky */
            top: 0; /* Stick to the top */
            z-index: 1000; /* Ensure it stays on top */
        }

        .logo {
            font-size: 30px;
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
            font-weight: 600;
            margin-left: 2%;
        }

        nav {
            margin-left: auto;
        }

        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            display: flex;
        }

        nav li {
            margin-right: 20px;
        }

        nav a {
            color: #fff;
            text-decoration: none;
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
            font-weight: 600;
            position: relative;
            padding: 5px 0; /* Added padding for better click area */
        }

        nav a::after {
            content: '';
            display: block;
            width: 0;
            height: 2px;
            background: #ccc;
            transition: width .3s;
            position: absolute;
            bottom: 0;
            left: 0;
        }

        nav a:hover::after {
            width: 100%; /* Animate underline on hover */
            background-color: #ccc;
        }

        .mySlides {
            position: relative;
            animation: slideIn 1s; /* Add animation to each slide */
            animation-delay: 2s; /* Add delay between loops */
            transition: opacity 1s; /* Add transition effect */
        }

        .mySlides.fade {
            animation: slideOut 2s; /* Add animation to each slide when it's fading out */
            transition: opacity 2s; /* Add transition effect */
        }
 

        .mySlides img {
                width: 100%; /* Make the image full width */
                height: 600px; /* Set a fixed height for all images */
                object-fit: cover; /* Cover the entire slide container */
                object-position: center; /* Center the image horizontally and vertically */
                filter: blur(1px);
        }

        .text {
                position: absolute; /* Position the text overlay absolutely */
                top: 50%; /* Center the text vertically */
                left: 40%; /* Center the text horizontally */
                transform: translate(-50%, -50%); /* Adjust the text position */
                color: #ffffff; /* White text color */
                font-size: 40px; /* Increase font size */
                font-weight: bold; /* Make the text bold */
                text-shadow: 0 0 10px #000000, 0 0 20px #000000, 0 0 30px #000000; /* Add a glow effect to the text */

                
        }

        .button-container {
                position: absolute; /* Position the button container absolutely */
                bottom: 30%; /* Position the button at the bottom of the slide */
                left: 80%; /* Center the button horizontally */
                transform: translateX(-50%); /* Adjust the button position */
                border-radius: 3%;
        }



        @keyframes slideIn {
            from {
                opacity: 1;
            }
            to {
                opacity: 0;
            }
        }

        @keyframes slideOut {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }
        .slide-button {
            background-color: #930808; /* Green background color */
            color: #fff; /* White text color */
            padding: 10px 20px; /* Add padding */
            font-size: 16px; /* Increase font size */
            cursor: pointer; /* Change cursor to pointer on hover */
            border: none;
            border-radius: 10% ;
        }

        .slide-button:hover {
            background-color: #6d0505; /* Darker green background color on hover */
        }
</style>
</head>
<body>
<header>
    <div class="logo">
        <p>MyUniform.com</p>
    </div>
    <nav>
        <ul>
            <li><a href="product/">PRODUCT</a></li>
            <li><a href="profile/user_email">PROFILE</a></li>
            <li><a href="login/">SIGN UP/LOG IN</a></li>
        </ul>
    </nav>
</header>   
<main>
    <div class="slideshow-container">
        <!-- Slideshow content -->
        <div class="mySlides fade">
            <img src="/static/gambar/slide1.webp" style="width:100%">
            <div class="text">"SHOP WITH US ON 27-28 JULY FOR FREE DELIVERY!"</div>
            <div class="button-container">
                <button class="slide-button">View Product</button>
            </div>
        </div>
        
        <div class="mySlides fade">
            <img src="/static/gambar/slide2.png" style="width:100%">
            <div class="text">"SHOP WITH US ON 27-28 JULY FOR FREE DELIVERY!"</div>
            <div class="button-container">
                <a href="product"><button class="slide-button">View Product</button></a>
            </div>
        </div>
        
        <div class="mySlides fade">
            <img src="/static/gambar/slide3.png" style="width:100%">
            <div class="text">"SHOP WITH US ON 27-28 JULY FOR FREE DELIVERY!"</div>
            <div class="button-container">
                <a href="product"><button class="slide-button">View Product</button></a>
            </div>
        </div>
    </div>
    <script>
        let slideIndex = 0;
        showSlides();

        function showSlides() {
            let i;
            let slides = document.getElementsByClassName("mySlides");
            let dots = document.getElementsByClassName("dot");

            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
            }

            slideIndex++;
            if (slideIndex > slides.length) { slideIndex = 1 }

            slides[slideIndex - 1].style.display = "block";
            setTimeout(showSlides, 5000); // Change image every 5 seconds
        }

        function plusSlides(n) {
            showSlides(slideIndex += n);
        }
    </script>
</main>
</body>
</html>

MyUnifoorm/templates/orderhistory.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
        }
        header {
            background-color: #6d0505;
            color: #fff;
            padding: 2px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            position: sticky;
            top: 0;
            z-index: 1000;
        }
        .logo {
            font-size: 30px;
            font-weight: 600;
            margin-left: 2%;
        }
        nav {
            margin-left: auto;
        }
        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            display: flex;
        }
        nav li {
            margin-right: 20px;
        }
        nav a {
            color: #fff;
            text-decoration: none;
            font-weight: 600;
            position: relative;
            padding: 5px 0;
        }
        nav a::after {
            content: '';
            display: block;
            width: 0;
            height: 2px;
            background: #ccc;
            transition: width .3s;
            position: absolute;
            bottom: 0;
            left: 0;
        }
        nav a:hover::after {
            width: 100%;
            background-color: #ccc;
        }
        main {
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }
        h1 {
            font-size: 24px;
            margin-bottom: 10px;
        }
        .order-container {
            padding: 20px;
            margin-bottom: 20px;
            background-color: #fff;
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .order-container p {
            margin: 5px 0;
            border-radius: 5px;
        }
        form {
            margin-top: 10px;
        }
        button[type="submit"] {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .cancel-button {
            background-color: #f44336;
            color: #fff;
        }
        .cancel-button:hover {
            background-color: #d32f2f;
        }
        .update-button {
            background-color: #4CAF50;
            color: #fff;
        }
        .update-button:hover {
            background-color: #3e8e41;
        }
    </style>
</head>
<body>
    <header>
        <div class="logo">
            <p>MyUniform.com</p>
        </div>
        <nav>
            <ul>
                <li><a href="/MyUnifoorm/">HOME</a></li>
                <li><a href="/MyUnifoorm/product/">PRODUCT</a></li>
            </ul>
        </nav>
    </header>  
    <main>
        <h1>My Orders</h1>
        {% for order in orders %}
        <div class="order-container">
            <p>Name: {{ order.Email.Name }}</p>
            <p>Order ID: {{ order.OrderID }}</p>
            <p>Product Name: {{ order.ProductID.ProductName }}</p>
            <p>Product Quantity: {{ order.Qty }}</p>
            <p>Order Date: {{ order.OrderDate }}</p>
            <p>Order Status: {{ order.OrderStatus }}</p>
            <p>Shipping Address {{order.Email.Address}}</p>
            <p>Total Amount: RM {{ order.TotalAmount|floatformat:2 }}</p>
            <form action="{% url 'delete_order' order.OrderID %}" method="post">
                {% csrf_token %}
                <button type="submit" class="cancel-button">Cancel Order</button>
            </form>
            <form action="{% url 'update_order' order.OrderID %}" method="get">
                <button type="submit" class="update-button">Update Order</button>
            </form>
        </div>
        {% empty %}
        <p>No orders found.</p>
        {% endfor %}
    </main>
</body>
</html>

MyUnifoorm/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>
<style>
        body {
            margin: 0;
            padding: 0;

        }

        header {
            background-color: #6d0505;
            color: #fff;
            padding: 2px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Added shadow for depth */
            position: sticky; /* Make header sticky */
            top: 0; /* Stick to the top */
            z-index: 1000; /* Ensure it stays on top */
        }

        .logo {
            font-size: 30px;
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
            font-weight: 600;
            margin-left: 2%;
        }

        nav {
            margin-left: auto;
        }

        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            display: flex;
        }

        nav li {
            margin-right: 20px;
        }

        nav a {
            color: #fff;
            text-decoration: none;
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
            font-weight: 600;
            position: relative;
            padding: 5px 0; /* Added padding for better click area */
        }

        nav a::after {
            content: '';
            display: block;
            width: 0;
            height: 2px;
            background: #ccc;
            transition: width .3s;
            position: absolute;
            bottom: 0;
            left: 0;
        }

        nav a:hover::after {
            width: 100%; /* Animate underline on hover */
            color : #ccc
        }
        .container {
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 1%;
        }

        h1 {
            margin-top: 0;
        }

        form {
            margin-top: 20px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 10px;
        }

        input[type="text"], input[type="password"], input[type="email"] {
            width: 100%;
            height: 40px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
        }
        .username {
        color: #00698f;
        }

        .btn-primary{
            background-color: #1477b1;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .btn-primary:hover {

            background-color: #4CAF50;
        }
 
        .logout-button {
            background-color: #ff0000;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        .logout-button:hover {
            background-color: #cc0000;
        }
</style>
<body>
    <header>
        <div class="logo">
            <p>MyUniform.com</p>
        </div>
        <nav>
            <ul>
                <li><a href="/MyUnifoorm/">HOME</a></li>
            </ul>
        </nav>
    </header>  
    <div class="container">
        <center><h1>Profile: <span style="color: #00698f;">{{ user.Name }}</span></h1></center>
        <p>Email: {{ user.Email }}</p>

        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_Password">Password:</label>
                <input type="password" class="form-control" id="id_Password" name="Password" maxlength="12" value="{{ user.Password }}">
            </div>
            <div class="form-group">
                <label for="id_Name">Name:</label>
                <input type="text" class="form-control" id="id_Name" name="Name" value="{{ user.Name }}">
            </div>
            <div class="form-group">
                <label for="id_PhoneNumber">Phone Number:</label>
                <input type="text" class="form-control" id="id_PhoneNumber" name="PhoneNumber" maxlength="13" value="{{ user.PhoneNumber }}">
            </div>
            <div class="form-group">
                <label for="id_Address">Address:</label>
                <input type="text" class="form-control" id="id_Address" name="Address" value="{{ user.Address }}">
            </div>
            <button type="submit" class="btn-primary">Update</button>
        </form>


        <form action="{% url 'logout' %}" method="post" style="margin-top: 20px;">
            {% csrf_token %}
            <button type="submit" class="logout-button">Logout</button>
        </form>
        
    </div>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
</body>
</html>